/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sante
         * @description L'API tourne.
         */
        get: operations["sante_api_sante_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sante/base": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sante Base
         * @description L'API tourne et la base de données répond.
         */
        get: operations["sante_base_api_sante_base_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/reglages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reglages */
        get: operations["reglages_api_comptes_reglages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/inscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscription
         * @description Crée un compte et envoie l'email de confirmation.
         *
         *     Si l'email a déjà un compte, la réponse est la même : on ne révèle pas qui est inscrit.
         *     Le titulaire de l'adresse reçoit un email qui le lui signale.
         *
         *     Sans vérification de l'email (ADR 0023), le compte est utilisable tout de suite,
         *     et une adresse déjà inscrite est signalée : personne d'autre ne pourrait prévenir son titulaire.
         */
        post: operations["inscription_api_comptes_inscription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmation
         * @description Confirme l'adresse d'un nouveau compte, ou la nouvelle adresse d'un compte existant.
         */
        post: operations["confirmation_api_comptes_confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/renvoyer-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renvoyer Confirmation */
        post: operations["renvoyer_confirmation_api_comptes_renvoyer_confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/connexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connexion */
        post: operations["connexion_api_comptes_connexion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/deconnexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deconnexion */
        post: operations["deconnexion_api_comptes_deconnexion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/moi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Moi */
        get: operations["moi_api_comptes_moi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifier Profil */
        patch: operations["modifier_profil_api_comptes_moi_patch"];
        trace?: never;
    };
    "/api/comptes/moi/mot-de-passe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changer Mot De Passe
         * @description Change le mot de passe et déconnecte les autres appareils.
         */
        post: operations["changer_mot_de_passe_api_comptes_moi_mot_de_passe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/moi/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changer Email
         * @description Envoie un lien à la nouvelle adresse. Elle ne remplace l'ancienne qu'après confirmation.
         *
         *     Sans vérification de l'email (ADR 0023), la nouvelle adresse remplace l'ancienne tout de suite.
         */
        post: operations["changer_email_api_comptes_moi_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/mot-de-passe-oublie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mot De Passe Oublie
         * @description Envoie un lien de réinitialisation. Même réponse si l'email est inconnu.
         */
        post: operations["mot_de_passe_oublie_api_comptes_mot_de_passe_oublie_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/reinitialisation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reinitialisation
         * @description Change le mot de passe et ferme toutes les sessions.
         */
        post: operations["reinitialisation_api_comptes_reinitialisation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/utilisateurs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister Utilisateurs */
        get: operations["lister_utilisateurs_api_admin_utilisateurs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/utilisateurs/{utilisateur_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifier Utilisateur */
        patch: operations["modifier_utilisateur_api_admin_utilisateurs__utilisateur_id__patch"];
        trace?: never;
    };
    "/api/admin/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister Themes */
        get: operations["lister_themes_api_admin_themes_get"];
        put?: never;
        /** Creer Theme */
        post: operations["creer_theme_api_admin_themes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/themes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprimer Theme */
        delete: operations["supprimer_theme_api_admin_themes__slug__delete"];
        options?: never;
        head?: never;
        /** Renommer Theme */
        patch: operations["renommer_theme_api_admin_themes__slug__patch"];
        trace?: never;
    };
    "/api/admin/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulter Journal
         * @description Les actions les plus récentes d'abord. Conservées un an (ADR 0014).
         */
        get: operations["consulter_journal_api_admin_journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/moi/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telecharger Mes Donnees */
        get: operations["telecharger_mes_donnees_api_comptes_moi_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/moi/suppression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Supprimer Mon Compte
         * @description Supprime le compte pour de bon. Le mot de passe est redemandé.
         */
        post: operations["supprimer_mon_compte_api_comptes_moi_suppression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lecons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister Lecons */
        get: operations["lister_lecons_api_lecons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lecons/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister Themes */
        get: operations["lister_themes_api_lecons_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lecons/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire Lecon */
        get: operations["lire_lecon_api_lecons__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parcours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister Parcours */
        get: operations["lister_parcours_api_parcours_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parcours/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire Parcours */
        get: operations["lire_parcours_api_parcours__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progression/lecons/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Terminer Lecon
         * @description Marque la leçon comme terminée. Sans effet si elle l'est déjà.
         */
        put: operations["terminer_lecon_api_progression_lecons__slug__put"];
        post?: never;
        /**
         * Reprendre Lecon
         * @description Retire la leçon des leçons terminées.
         */
        delete: operations["reprendre_lecon_api_progression_lecons__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Espace */
        get: operations["espace_api_progression_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyser Fichier
         * @description Vérifie le fichier sans rien enregistrer. Le navigateur exécute ensuite les codes listés.
         */
        post: operations["analyser_fichier_api_imports_analyse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importer Fichier
         * @description Crée une révision « brouillon » par leçon. Le fichier est réanalysé : tout ou rien.
         */
        post: operations["importer_fichier_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relecture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File De Relecture */
        get: operations["file_de_relecture_api_relecture_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relecture/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire Revision */
        get: operations["lire_revision_api_relecture__revision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relecture/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decider En Groupe
         * @description Applique la même décision à plusieurs versions. C'est tout ou rien.
         */
        post: operations["decider_en_groupe_api_relecture_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relecture/{revision_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decider */
        post: operations["decider_api_relecture__revision_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mes Contributions */
        get: operations["mes_contributions_api_contributions_get"];
        put?: never;
        /** Nouvelle Lecon */
        post: operations["nouvelle_lecon_api_contributions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributions/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lire Contribution */
        get: operations["lire_contribution_api_contributions__revision_id__get"];
        /** Enregistrer */
        put: operations["enregistrer_api_contributions__revision_id__put"];
        post?: never;
        /**
         * Supprimer
         * @description Supprime un brouillon jamais soumis. Une leçon qui n'a plus aucune version disparaît.
         */
        delete: operations["supprimer_api_contributions__revision_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributions/depuis/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proposer Modification
         * @description Brouillon copié de la version en ligne, ou la proposition déjà ouverte s'il y en a une.
         */
        post: operations["proposer_modification_api_contributions_depuis__slug__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributions/{revision_id}/reprendre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprendre
         * @description Après « demander des corrections » : nouveau brouillon copié de la version relue.
         */
        post: operations["reprendre_api_contributions__revision_id__reprendre_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contributions/{revision_id}/soumettre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soumettre */
        post: operations["soumettre_api_contributions__revision_id__soumettre_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recherche": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rechercher
         * @description Sans mots, renvoie tout ce qui correspond aux filtres, par ordre alphabétique.
         */
        get: operations["rechercher_api_recherche_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action */
        Action: {
            /** Id */
            id: number;
            /** Action */
            action: string;
            /** Acteur */
            acteur: string;
            /** Cible */
            cible: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /**
             * Cree Le
             * Format: date-time
             */
            cree_le: string;
        };
        /** ActionExportee */
        ActionExportee: {
            /** Action */
            action: string;
            /** Cible */
            cible: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /**
             * Le
             * Format: date-time
             */
            le: string;
        };
        /** ApercuLecon */
        ApercuLecon: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /** Theme */
            theme: string;
            /**
             * Action
             * @enum {string}
             */
            action: "creation" | "nouvelle_version";
            /** Nb Images */
            nb_images: number;
        };
        /** ApercuParcours */
        ApercuParcours: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /**
             * Action
             * @enum {string}
             */
            action: "creation" | "mise_a_jour";
            /** Lecons */
            lecons: string[];
        };
        /** Body_analyser_fichier_api_imports_analyse_post */
        Body_analyser_fichier_api_imports_analyse_post: {
            /** Fichier */
            fichier: string;
        };
        /** Body_importer_fichier_api_imports_post */
        Body_importer_fichier_api_imports_post: {
            /** Fichier */
            fichier: string;
        };
        /** ChangementEmail */
        ChangementEmail: {
            /**
             * Nouvel Email
             * Format: email
             */
            nouvel_email: string;
            /** Mot De Passe */
            mot_de_passe: string;
        };
        /** ChangementMotDePasse */
        ChangementMotDePasse: {
            /** Actuel */
            actuel: string;
            /** Nouveau */
            nouveau: string;
        };
        /**
         * CodeAVerifier
         * @description Exemple de code à exécuter dans le navigateur de la personne qui importe (ADR 0009).
         */
        CodeAVerifier: {
            /** Lecon */
            lecon: string;
            /** Bloc */
            bloc: number;
            /**
             * Langage
             * @enum {string}
             */
            langage: "python" | "javascript";
            /** Code */
            code: string;
            /** Sortie Attendue */
            sortie_attendue: string | null;
            /**
             * Solution
             * @default false
             */
            solution: boolean;
        };
        /** CompteExporte */
        CompteExporte: {
            /** Email */
            email: string;
            /** Pseudo */
            pseudo: string;
            role: components["schemas"]["Role"];
            /**
             * Inscrit Le
             * Format: date-time
             */
            inscrit_le: string;
            /** Email Confirme Le */
            email_confirme_le: string | null;
            /** Licence Acceptee Le */
            licence_acceptee_le: string | null;
        };
        /** Connexion */
        Connexion: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Mot De Passe */
            mot_de_passe: string;
        };
        /**
         * ContenuBrouillon
         * @description Un brouillon peut être incomplet : seules les longueurs maximales sont vérifiées ici.
         */
        ContenuBrouillon: {
            /** Titre */
            titre: string;
            /** Resume */
            resume: string;
            /** Objectifs */
            objectifs: string[];
            /** Duree Minutes */
            duree_minutes: number;
            /** Contenu */
            contenu: string;
            /** Theme */
            theme?: string | null;
            niveau?: components["schemas"]["Niveau"] | null;
        };
        /** Contribution */
        Contribution: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Lecon Slug */
            lecon_slug: string;
            /** Numero */
            numero: number;
            statut: components["schemas"]["StatutRevision"];
            /** Titre */
            titre: string;
            /** Resume */
            resume: string;
            /** Objectifs */
            objectifs: string[];
            /** Duree Minutes */
            duree_minutes: number;
            /** Contenu */
            contenu: string;
            theme: components["schemas"]["ThemeLecture"];
            niveau: components["schemas"]["Niveau"];
            /** Nouvelle Lecon */
            nouvelle_lecon: boolean;
            /**
             * Modifiee Le
             * Format: date-time
             */
            modifiee_le: string;
            /** Retours */
            retours: components["schemas"]["Retour"][];
        };
        /**
         * Decision
         * @description Les trois décisions d'un relecteur (ADR 0010).
         * @enum {string}
         */
        Decision: "publier" | "corriger" | "refuser";
        /** DecisionLue */
        DecisionLue: {
            decision: components["schemas"]["Decision"];
            /** Relecteur */
            relecteur: string;
            /** Commentaire */
            commentaire: string | null;
            /**
             * Cree Le
             * Format: date-time
             */
            cree_le: string;
        };
        /** DemandeDecision */
        DemandeDecision: {
            decision: components["schemas"]["Decision"];
            /** Commentaire */
            commentaire?: string | null;
        };
        /**
         * DemandeDecisionGroupee
         * @description La même décision pour plusieurs versions, par exemple toutes celles d'un import.
         */
        DemandeDecisionGroupee: {
            decision: components["schemas"]["Decision"];
            /** Commentaire */
            commentaire?: string | null;
            /** Revision Ids */
            revision_ids: string[];
        };
        /** DemandeParEmail */
        DemandeParEmail: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** DemandeSuppression */
        DemandeSuppression: {
            /** Mot De Passe */
            mot_de_passe: string;
        };
        /** ElementContribution */
        ElementContribution: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Lecon Slug */
            lecon_slug: string;
            /** Titre */
            titre: string;
            /** Numero */
            numero: number;
            statut: components["schemas"]["StatutRevision"];
            /** Nouvelle Lecon */
            nouvelle_lecon: boolean;
            /**
             * Modifiee Le
             * Format: date-time
             */
            modifiee_le: string;
        };
        /** ElementFile */
        ElementFile: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Lecon Slug */
            lecon_slug: string;
            /** Titre */
            titre: string;
            /** Numero */
            numero: number;
            statut: components["schemas"]["StatutRevision"];
            /** Auteur */
            auteur: string;
            /** Assiste Par Ia */
            assiste_par_ia: boolean;
            /** Fichier Importe */
            fichier_importe: string | null;
            /**
             * Cree Le
             * Format: date-time
             */
            cree_le: string;
            /** Peut Publier */
            peut_publier: boolean;
        };
        /** Erreur */
        Erreur: {
            /** Emplacement */
            emplacement: string;
            /** Message */
            message: string;
        };
        /**
         * Espace
         * @description Tableau de bord de l'apprenant (cadrage § 5.3).
         */
        Espace: {
            /** Lecons Terminees */
            lecons_terminees: number;
            /** Pourcentage */
            pourcentage: number;
            /** Parcours En Cours */
            parcours_en_cours: components["schemas"]["ResumeParcours"][];
            /** Parcours Termines */
            parcours_termines: components["schemas"]["ResumeParcours"][];
        };
        /** EtapeLecture */
        EtapeLecture: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /** Duree Minutes */
            duree_minutes: number;
            /** Terminee */
            terminee: boolean;
        };
        /**
         * Export
         * @description Tout ce que la plateforme garde sur toi. Le mot de passe n'est stocké que haché.
         */
        Export: {
            /**
             * Format
             * @default renard-etudiant/donnees-personnelles
             */
            format: string;
            /**
             * Exporte Le
             * Format: date-time
             */
            exporte_le: string;
            compte: components["schemas"]["CompteExporte"];
            /** Sessions */
            sessions: components["schemas"]["SessionExportee"][];
            /** Lecons Terminees */
            lecons_terminees: components["schemas"]["LeconTermineeExportee"][];
            /** Contributions */
            contributions: components["schemas"]["VersionExportee"][];
            /** Relectures */
            relectures: components["schemas"]["RelectureExportee"][];
            /** Imports */
            imports: components["schemas"]["ImportExporte"][];
            /** Actions */
            actions: components["schemas"]["ActionExportee"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportExporte */
        ImportExporte: {
            /** Fichier */
            fichier: string;
            /** Nb Lecons */
            nb_lecons: number;
            /**
             * Le
             * Format: date-time
             */
            le: string;
        };
        /** Inscription */
        Inscription: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Pseudo */
            pseudo: string;
            /** Mot De Passe */
            mot_de_passe: string;
        };
        /** JetonRecu */
        JetonRecu: {
            /** Jeton */
            jeton: string;
        };
        /** LeconPubliee */
        LeconPubliee: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /** Resume */
            resume: string;
            theme: components["schemas"]["ThemeLecture"];
            niveau: components["schemas"]["Niveau"];
            /** Duree Minutes */
            duree_minutes: number;
            /** Objectifs */
            objectifs: string[];
            /** Contenu */
            contenu: string;
            /** Assiste Par Ia */
            assiste_par_ia: boolean;
            /** Auteurs */
            auteurs: string[];
            /**
             * Publiee Le
             * Format: date-time
             */
            publiee_le: string;
            /** Terminee */
            terminee: boolean;
        };
        /** LeconTermineeExportee */
        LeconTermineeExportee: {
            /** Lecon */
            lecon: string;
            /**
             * Terminee Le
             * Format: date-time
             */
            terminee_le: string;
        };
        /** ModificationProfil */
        ModificationProfil: {
            /** Pseudo */
            pseudo: string;
        };
        /** ModificationTheme */
        ModificationTheme: {
            /** Nom */
            nom: string;
        };
        /** ModificationUtilisateur */
        ModificationUtilisateur: {
            role?: components["schemas"]["Role"] | null;
            /** Suspendu */
            suspendu?: boolean | null;
        };
        /**
         * Moi
         * @description L'utilisateur connecté. Le jeton CSRF est à renvoyer dans l'en-tête X-CSRF-Token.
         */
        Moi: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Pseudo */
            pseudo: string;
            role: components["schemas"]["Role"];
            /** Licence Acceptee */
            licence_acceptee: boolean;
            /** Jeton Csrf */
            jeton_csrf: string;
        };
        /**
         * Niveau
         * @enum {string}
         */
        Niveau: "debutant" | "intermediaire";
        /** NouveauTheme */
        NouveauTheme: {
            /** Slug */
            slug: string;
            /** Nom */
            nom: string;
        };
        /** NouvelleLecon */
        NouvelleLecon: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /** Theme */
            theme: string;
            niveau: components["schemas"]["Niveau"];
        };
        /** PageJournal */
        PageJournal: {
            /** Actions */
            actions: components["schemas"]["Action"][];
            /** Total */
            total: number;
        };
        /** PageUtilisateurs */
        PageUtilisateurs: {
            /** Utilisateurs */
            utilisateurs: components["schemas"]["UtilisateurAdmin"][];
            /** Total */
            total: number;
        };
        /** ParcoursDetail */
        ParcoursDetail: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /** Description */
            description: string;
            niveau: components["schemas"]["Niveau"];
            theme: components["schemas"]["ThemeLecture"];
            /** Nb Lecons */
            nb_lecons: number;
            /** Nb Terminees */
            nb_terminees: number;
            /** Duree Minutes */
            duree_minutes: number;
            /** Lecons */
            lecons: components["schemas"]["EtapeLecture"][];
            /** Prochaine Lecon */
            prochaine_lecon: string | null;
        };
        /**
         * Reglages
         * @description Réglages publics des comptes, pour adapter les écrans du front.
         */
        Reglages: {
            /** Verification Email */
            verification_email: boolean;
        };
        /** Reinitialisation */
        Reinitialisation: {
            /** Jeton */
            jeton: string;
            /** Nouveau */
            nouveau: string;
        };
        /** RelectureExportee */
        RelectureExportee: {
            /** Lecon */
            lecon: string;
            /** Version */
            version: number;
            decision: components["schemas"]["Decision"];
            /** Commentaire */
            commentaire: string | null;
            /**
             * Le
             * Format: date-time
             */
            le: string;
        };
        /** ResultatAnalyse */
        ResultatAnalyse: {
            /** Valide */
            valide: boolean;
            /** Erreurs */
            erreurs: components["schemas"]["Erreur"][];
            /** Lecons */
            lecons: components["schemas"]["ApercuLecon"][];
            parcours: components["schemas"]["ApercuParcours"] | null;
            /** Codes */
            codes: components["schemas"]["CodeAVerifier"][];
            /** Assiste Par Ia */
            assiste_par_ia: boolean;
            /** Outil */
            outil: string | null;
        };
        /** ResultatDecisionGroupee */
        ResultatDecisionGroupee: {
            /** Revision Ids */
            revision_ids: string[];
        };
        /** ResultatImport */
        ResultatImport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revisions */
            revisions: components["schemas"]["RevisionCreee"][];
        };
        /** ResultatLecon */
        ResultatLecon: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            theme: components["schemas"]["ThemeLecture"];
            niveau: components["schemas"]["Niveau"];
            /** Duree Minutes */
            duree_minutes: number;
            /** Terminee */
            terminee: boolean;
            /** Resume */
            resume: components["schemas"]["Segment"][];
            /** Extrait */
            extrait: components["schemas"]["Segment"][];
        };
        /** ResultatParcours */
        ResultatParcours: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            theme: components["schemas"]["ThemeLecture"];
            niveau: components["schemas"]["Niveau"];
            /** Nb Lecons */
            nb_lecons: number;
            /** Nb Terminees */
            nb_terminees: number;
            /** Duree Minutes */
            duree_minutes: number;
            /** Description */
            description: components["schemas"]["Segment"][];
        };
        /** Resultats */
        Resultats: {
            /** Parcours */
            parcours: components["schemas"]["ResultatParcours"][];
            /** Lecons */
            lecons: components["schemas"]["ResultatLecon"][];
        };
        /** ResumeLecon */
        ResumeLecon: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /** Resume */
            resume: string;
            theme: components["schemas"]["ThemeLecture"];
            niveau: components["schemas"]["Niveau"];
            /** Duree Minutes */
            duree_minutes: number;
        };
        /** ResumeParcours */
        ResumeParcours: {
            /** Slug */
            slug: string;
            /** Titre */
            titre: string;
            /** Description */
            description: string;
            niveau: components["schemas"]["Niveau"];
            theme: components["schemas"]["ThemeLecture"];
            /** Nb Lecons */
            nb_lecons: number;
            /** Nb Terminees */
            nb_terminees: number;
            /** Duree Minutes */
            duree_minutes: number;
        };
        /** Retour */
        Retour: {
            decision: components["schemas"]["Decision"];
            /** Relecteur */
            relecteur: string;
            /** Commentaire */
            commentaire: string | null;
            /**
             * Cree Le
             * Format: date-time
             */
            cree_le: string;
        };
        /** RevisionARelire */
        RevisionARelire: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Lecon Slug */
            lecon_slug: string;
            /** Numero */
            numero: number;
            statut: components["schemas"]["StatutRevision"];
            /** Titre */
            titre: string;
            /** Resume */
            resume: string;
            /** Objectifs */
            objectifs: string[];
            /** Duree Minutes */
            duree_minutes: number;
            /** Contenu */
            contenu: string;
            theme: components["schemas"]["ThemeLecture"];
            niveau: components["schemas"]["Niveau"];
            /** Auteur */
            auteur: string;
            /** Assiste Par Ia */
            assiste_par_ia: boolean;
            /** Fichier Importe */
            fichier_importe: string | null;
            /** A Relire */
            a_relire: boolean;
            /** Peut Publier */
            peut_publier: boolean;
            /** Historique */
            historique: components["schemas"]["VersionHistorique"][];
        };
        /** RevisionCreee */
        RevisionCreee: {
            /** Slug */
            slug: string;
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
        };
        /**
         * Role
         * @description Rôles du cadrage, du moins au plus élevé. Chaque rôle a les droits des précédents.
         * @enum {string}
         */
        Role: "apprenant" | "contributeur" | "relecteur" | "admin";
        /**
         * Segment
         * @description Morceau de texte. Les mots trouvés sont dans des segments surlignés.
         */
        Segment: {
            /** Texte */
            texte: string;
            /** Surligne */
            surligne: boolean;
        };
        /** SessionExportee */
        SessionExportee: {
            /**
             * Ouverte Le
             * Format: date-time
             */
            ouverte_le: string;
            /**
             * Expire Le
             * Format: date-time
             */
            expire_le: string;
        };
        /** Soumission */
        Soumission: {
            /**
             * Accepte Licence
             * @default false
             */
            accepte_licence: boolean;
        };
        /** Statut */
        Statut: {
            /**
             * Statut
             * @constant
             */
            statut: "ok";
        };
        /**
         * StatutRevision
         * @description Statuts du circuit de relecture (ADR 0010).
         * @enum {string}
         */
        StatutRevision: "brouillon" | "en_relecture" | "a_corriger" | "publiee" | "refusee";
        /** ThemeAdmin */
        ThemeAdmin: {
            /** Slug */
            slug: string;
            /** Nom */
            nom: string;
            /** Nb Lecons */
            nb_lecons: number;
            /** Nb Parcours */
            nb_parcours: number;
        };
        /** ThemeLecture */
        ThemeLecture: {
            /** Slug */
            slug: string;
            /** Nom */
            nom: string;
        };
        /**
         * TypeResultat
         * @enum {string}
         */
        TypeResultat: "lecon" | "parcours";
        /** UtilisateurAdmin */
        UtilisateurAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Pseudo */
            pseudo: string;
            role: components["schemas"]["Role"];
            /** Email Verifie */
            email_verifie: boolean;
            /** Suspendu */
            suspendu: boolean;
            /**
             * Cree Le
             * Format: date-time
             */
            cree_le: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionExportee */
        VersionExportee: {
            /** Lecon */
            lecon: string;
            /** Numero */
            numero: number;
            statut: components["schemas"]["StatutRevision"];
            /** Titre */
            titre: string;
            /** Resume */
            resume: string;
            /** Objectifs */
            objectifs: string[];
            /** Duree Minutes */
            duree_minutes: number;
            /** Contenu */
            contenu: string;
            /**
             * Creee Le
             * Format: date-time
             */
            creee_le: string;
            /**
             * Modifiee Le
             * Format: date-time
             */
            modifiee_le: string;
            /** Publiee Le */
            publiee_le: string | null;
        };
        /** VersionHistorique */
        VersionHistorique: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Numero */
            numero: number;
            statut: components["schemas"]["StatutRevision"];
            /** Auteur */
            auteur: string;
            /**
             * Cree Le
             * Format: date-time
             */
            cree_le: string;
            /** Publiee Le */
            publiee_le: string | null;
            /** En Ligne */
            en_ligne: boolean;
            /** Decisions */
            decisions: components["schemas"]["DecisionLue"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sante_api_sante_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statut"];
                };
            };
        };
    };
    sante_base_api_sante_base_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statut"];
                };
            };
        };
    };
    reglages_api_comptes_reglages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reglages"];
                };
            };
        };
    };
    inscription_api_comptes_inscription_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Inscription"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmation_api_comptes_confirmation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JetonRecu"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renvoyer_confirmation_api_comptes_renvoyer_confirmation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeParEmail"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connexion_api_comptes_connexion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Connexion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Moi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deconnexion_api_comptes_deconnexion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moi_api_comptes_moi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Moi"];
                };
            };
        };
    };
    modifier_profil_api_comptes_moi_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationProfil"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Moi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changer_mot_de_passe_api_comptes_moi_mot_de_passe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangementMotDePasse"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changer_email_api_comptes_moi_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangementEmail"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mot_de_passe_oublie_api_comptes_mot_de_passe_oublie_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeParEmail"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reinitialisation_api_comptes_reinitialisation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reinitialisation"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lister_utilisateurs_api_admin_utilisateurs_get: {
        parameters: {
            query?: {
                /** @description Début du pseudo ou de l'email */
                q?: string;
                limite?: number;
                decalage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageUtilisateurs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modifier_utilisateur_api_admin_utilisateurs__utilisateur_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                utilisateur_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationUtilisateur"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtilisateurAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lister_themes_api_admin_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeAdmin"][];
                };
            };
        };
    };
    creer_theme_api_admin_themes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NouveauTheme"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supprimer_theme_api_admin_themes__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renommer_theme_api_admin_themes__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationTheme"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consulter_journal_api_admin_journal_get: {
        parameters: {
            query?: {
                action?: string | null;
                limite?: number;
                decalage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageJournal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telecharger_mes_donnees_api_comptes_moi_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
        };
    };
    supprimer_mon_compte_api_comptes_moi_suppression_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeSuppression"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lister_lecons_api_lecons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeLecon"][];
                };
            };
        };
    };
    lister_themes_api_lecons_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeLecture"][];
                };
            };
        };
    };
    lire_lecon_api_lecons__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeconPubliee"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lister_parcours_api_parcours_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeParcours"][];
                };
            };
        };
    };
    lire_parcours_api_parcours__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcoursDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    terminer_lecon_api_progression_lecons__slug__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprendre_lecon_api_progression_lecons__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    espace_api_progression_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Espace"];
                };
            };
        };
    };
    analyser_fichier_api_imports_analyse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyser_fichier_api_imports_analyse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatAnalyse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importer_fichier_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importer_fichier_api_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatImport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_de_relecture_api_relecture_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementFile"][];
                };
            };
        };
    };
    lire_revision_api_relecture__revision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionARelire"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decider_en_groupe_api_relecture_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeDecisionGroupee"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatDecisionGroupee"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decider_api_relecture__revision_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionARelire"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mes_contributions_api_contributions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementContribution"][];
                };
            };
        };
    };
    nouvelle_lecon_api_contributions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NouvelleLecon"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lire_contribution_api_contributions__revision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enregistrer_api_contributions__revision_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContenuBrouillon"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supprimer_api_contributions__revision_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proposer_modification_api_contributions_depuis__slug__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprendre_api_contributions__revision_id__reprendre_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soumettre_api_contributions__revision_id__soumettre_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Soumission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rechercher_api_recherche_get: {
        parameters: {
            query?: {
                /** @description Mots recherchés */
                q?: string;
                theme?: string | null;
                niveau?: components["schemas"]["Niveau"] | null;
                type?: components["schemas"]["TypeResultat"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resultats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
